from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from daimon_esports_app import views
from rest_framework_simplejwt.views import TokenObtainPairView

urlpatterns = [
    path('', views.index),
    path('user/', views.UserView.as_view()),
    path('user/teams/', views.UserTeams.as_view()),
    path('user/tournaments/', views.UserTournaments.as_view()),
    path('user/requests/in/', views.UserRequestsIn.as_view()),
    path('user/requests/out/', views.UserRequestsIn.as_view()),
    path('user/register/', views.UserRegister.as_view()),
    path('user/login/', TokenObtainPairView.as_view()),
    path('user/modify/name/', views.UserName.as_view()),
    path('user/modify/username/', views.UserUserName.as_view()),
    path('user/modify/password/', views.UserPassword.as_view()),
    path('user/delete/', views.UserView.as_view()),
    path('disciplines/', views.DisciplineList.as_view()),
    path('tournaments/search/', views.TournamentSearch.as_view()),
    path('tournaments/create/', views.TournamentModify.as_view()),
    path('tournaments/<str:pk>/', views.TournamentDetail.as_view()),
    path('tournaments/<str:pk>/cansubscribe/', views.TournamentCanSubscribe.as_view()),
    path('tournaments/<str:pk>/modify/name/', views.TournamentName.as_view()),
    path('tournaments/<str:pk>/modify/discipline/', views.TournamentDiscipline.as_view()),
    path('tournaments/<str:pk>/modify/streaming_platform/', views.TournamentStreamingPlatform.as_view()),
    path('tournaments/<str:pk>/modify/meeting_platform/', views.TournamentMeetingPlatform.as_view()),
    path('tournaments/<str:pk>/modify/dates/', views.TournamentDates.as_view()),
    path('tournaments/<str:pk>/delete/', views.TournamentModify.as_view()),
    path('teams/create/', views.TeamModify.as_view()),
    path('teams/<str:pk>/', views.TeamDetail.as_view()),
    path('teams/<str:pk>/modify/', views.TeamModify.as_view()),
    path('teams/<str:pk>/modify/transferownership/', views.TeamTransferOwnership.as_view()),
    path('teams/<str:pk>/modify/logo/', views.TeamLogo.as_view()),
    path('teams/<str:pk>/delete/', views.TeamModify.as_view()),
    path('games/', views.GameList.as_view()),
    path('games/create/', views.GameModify.as_view()),
    path('games/<str:pk>/', views.GameDetail.as_view()),
    path('games/<str:pk>/modify/teams/', views.GameTeams.as_view()),
    path('games/<str:pk>/modify/score/', views.GameScore.as_view()),
    path('games/<str:pk>/modify/time/', views.GameTime.as_view()),
    path('games/<str:pk>/modify/minutes/', views.GameMinutes.as_view()),
    path('games/<str:pk>/delete/', views.GameModify.as_view()),
    path('players/<str:pk>/delete/', views.PlayerDetail.as_view()),
    path('requests/create/', views.RequestCreate.as_view()),
    path('requests/<str:pk>/accept/', views.RequestAccept.as_view()),
    path('requests/<str:pk>/delete/', views.RequestDetail.as_view()),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)