# Generated by Django 5.0.6 on 2024-07-06 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0004_rename_display_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roster',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='roster',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='game',
            name='roster1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='roster2',
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='daimon_esports_app.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='daimon_esports_app.team'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'team')},
        ),
    ]
