# Generated by Django 5.0.6 on 2024-08-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0007_request_team_alter_game_score1_alter_game_score2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
