# Generated by Django 5.0.6 on 2024-07-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=255)),
                ('organizer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sub_start', models.DateTimeField()),
                ('sub_stop', models.DateTimeField()),
                ('games_start', models.DateTimeField()),
                ('games_stop', models.DateTimeField()),
                ('team_count', models.IntegerField()),
                ('player_count', models.IntegerField()),
                ('meeting_platform', models.CharField(max_length=255)),
                ('streaming_platform', models.CharField(max_length=255)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.customuser')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('roster1', models.CharField(max_length=255)),
                ('roster2', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('minutes', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='daimon_esports_app.customuser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='daimon_esports_app.customuser')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.customuser')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.roster')),
            ],
            options={
                'unique_together': {('user', 'roster')},
            },
        ),
    ]
