# Generated by Django 5.0.6 on 2024-07-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
