# Generated by Django 5.0.6 on 2024-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='score2',
            field=models.IntegerField(null=True),
        ),
    ]
