# Generated by Django 5.0.6 on 2024-07-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0002_game_score1_game_score2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
