# Generated by Django 5.0.6 on 2024-07-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0003_alter_discipline_id_alter_game_id_alter_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='tag',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
