# Generated by Django 5.0.6 on 2024-07-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0004_roster_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='roster1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster1', to='daimon_esports_app.roster'),
        ),
        migrations.AlterField(
            model_name='game',
            name='roster2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster2', to='daimon_esports_app.roster'),
        ),
    ]
