# Generated by Django 5.0.6 on 2024-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0006_alter_user_options_rename_hash_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizer',
            field=models.BooleanField(default=False),
        ),
    ]
