# Generated by Django 5.0.6 on 2024-08-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daimon_esports_app', '0006_alter_game_team1_alter_game_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='team',
            field=models.ForeignKey(default='49b129d196a4', on_delete=django.db.models.deletion.CASCADE, to='daimon_esports_app.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='daimon_esports_app.tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='daimon_esports_app.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='daimon_esports_app.tournament'),
        ),
    ]
